spring.application.name=khieu

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Config JWT
jwt.base64-secret=${JWT_BASE64_SECRET}
access-token-validity-in-seconds=${ACCESS_TOKEN_VALIDITY_IN_SECONDS}
refresh-token-validity-in-seconds=${REFRESH_TOKEN_VALIDITY_IN_SECONDS}
